name: Update Lunch Menu

on:
  schedule:
    # Run at 8:00 AM Swedish time (UTC+1/UTC+2)
    - cron: '0 7 * * *'  # 7:00 UTC = 8:00 AM Swedish time (UTC+1)
  workflow_dispatch:  # Allow manual trigger

# Add permissions
permissions:
  contents: write
  pull-requests: write

jobs:
  update-lunch-menu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run lunch menu scraper
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python restaurant_scraper.py
        echo "Checking lunch_data.json contents:"
        ls -l lunch_data.json
        cat lunch_data.json
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lunch_data.json
        git status
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update lunch menu data" && git push) 